In [259]:
words = open('names.txt','r').read().splitlines()

In [260]:
b = {}

for w in words:
    chs = ["."] + list(w)+ ["."]
    for ch1,ch2 in zip(chs,chs[1:]):
        bigram = (ch1,ch2)
        b[bigram] = b.get(bigram,0)+1

In [261]:
sorted(b.items(),key=lambda kv:-kv[1])

[(('n', '.'), 6763),
 (('a', '.'), 6640),
 (('a', 'n'), 5438),
 (('.', 'a'), 4410),
 (('e', '.'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('.', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('.', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '.'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('.', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '.'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('.', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '.'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('.', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('.', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('.', 'l'), 1572),
 (('.', 'c'), 1542),
 (('.', 'e'), 1531),
 (('j', 'a'), 1473),
 (('r', '.'), 1377),
 (('n', 'e'),

In [262]:
chars = sorted(list(set(''.join(words))))

stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.']=0

itos = {i:s for s,i in stoi.items()}

In [263]:
import torch
from torch.nn import functional as f


In [264]:
N = torch.zeros((27,27),dtype=torch.int32)

In [265]:
for w in words:
    chs = ["."] + list(w)+ ["."]
    for ch1,ch2 in zip(chs,chs[1:]):
        N[stoi[ch1],stoi[ch2]]+=1

In [266]:
"""import matplotlib.pyplot as plt

plt.figure(figsize=(16,16))
plt.imshow(N,cmap='Blues')
for i in range(27):
    for j in range(27):
        chstr = itos[i] + itos[j]
        plt.text(j,i,chstr,ha="center",va = "bottom",color="gray")
        plt.text(j,i,N[i,j].item(),ha="center",va = "top",color="gray")

plt.axis("off")"""

'import matplotlib.pyplot as plt\n\nplt.figure(figsize=(16,16))\nplt.imshow(N,cmap=\'Blues\')\nfor i in range(27):\n    for j in range(27):\n        chstr = itos[i] + itos[j]\n        plt.text(j,i,chstr,ha="center",va = "bottom",color="gray")\n        plt.text(j,i,N[i,j].item(),ha="center",va = "top",color="gray")\n\nplt.axis("off")'

In [267]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [268]:
p = N[0].float()
p = p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [269]:
g = torch.Generator().manual_seed(2147483647)

ix = torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
itos[ix]

'm'

In [270]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3,generator=g)
p = p/p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [271]:
torch.multinomial(p,num_samples=20,replacement=True,generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [272]:
P = (N+1).float()
P /= P.sum(1,keepdim=True)

In [273]:
g = torch.Generator().manual_seed(2147483647)

ix = 0
for i in range(30):
    out=[]
    while True:
        p = P[ix]
        ix = torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
        out.append(itos[ix])
        if ix==0:
            break
    print(''.join(out))

mor.
axx.
minaymoryles.
kondlaisah.
anchshizarie.
odaren.
iaddash.
h.
jhinatien.
egushl.
h.
br.
a.
jayn.
ilemannariaenien.
be.
f.
akiinela.
trttanakeroruceyaaxatona.
lamoynayrkiedengin.
torrederahnn.
ellovyllobrqura.
ay.
h.
kn.
jaieendenelele.
kianu.
eryly.
zeeieil.
kayvirgjusinn.


In [274]:
log_likelihood = 0.0
n=0

for w in ['andrejq']:
    chs = ['.'] + list(w) + ['.']
    for ch1,ch2 in zip(chs,chs[1:]):    
        prob = P[stoi[ch1],stoi[ch2]]
        logprob = torch.log(prob)
        n+=1
        log_likelihood+=logprob
        print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f"{log_likelihood=}")
nll = -log_likelihood
print(f'{nll=}')
print({nll/n})

.a: 0.1376 -1.9835
an: 0.1604 -1.8302
nd: 0.0384 -3.2594
dr: 0.0770 -2.5646
re: 0.1334 -2.0143
ej: 0.0027 -5.9004
jq: 0.0003 -7.9817
q.: 0.0970 -2.3331
log_likelihood=tensor(-27.8672)
nll=tensor(27.8672)
{tensor(3.4834)}


In [275]:
xs=[]
ys=[]

for w in words:
    chs = ["."] + list(w)+ ["."]
    for ch1,ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print(f"Number of Samples : {num}")

g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27),generator=g,requires_grad=True)

Number of Samples : 228146


In [279]:
for k in range(100):
    xenc = f.one_hot(xs,num_classes=27).float()
    logits = xenc @ W
    count = logits.exp()
    probs =count/ count.sum(1,keepdim=True)
    loss = -probs[torch.arange(num),ys].log().mean()
    print(loss.item())
    W.grad=None
    loss.backward()
    W.data+=-50*W.grad

2.4623453617095947
2.462298631668091
2.462252140045166
2.4622061252593994
2.462161064147949
2.462116003036499
2.462071657180786
2.4620275497436523
2.461984395980835
2.4619412422180176
2.4618983268737793
2.4618561267852783
2.4618144035339355
2.461773157119751
2.4617323875427246
2.4616920948028564
2.4616520404815674
2.4616122245788574
2.4615728855133057
2.461534023284912
2.4614953994750977
2.4614572525024414
2.4614193439483643
2.4613821506500244
2.4613449573516846
2.461308240890503
2.4612717628479004
2.461236000061035
2.46120023727417
2.461164712905884
2.461129903793335
2.461095094680786
2.4610607624053955
2.461026906967163
2.4609928131103516
2.4609594345092773
2.4609262943267822
2.4608936309814453
2.4608609676361084
2.4608287811279297
2.460797071456909
2.4607653617858887
2.460733652114868
2.460702419281006
2.460671901702881
2.460641384124756
2.460610866546631
2.460580825805664
2.4605510234832764
2.4605214595794678
2.4604921340942383
2.460462808609009
2.4604339599609375
2.460405826568603

In [280]:
g = torch.Generator().manual_seed(2147483647)
for i in range(5):
    out = []
    ix =0
    while True:
        xenc = f.one_hot(torch.tensor([ix]),num_classes=27).float()
        logits = xenc@W
        counts = logits.exp()
        p = counts/counts.sum(1,keepdims = True)

        ix = torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
        out.append(itos[ix])

        if ix==0:
            break

    print(''.join(out))

mor.
axx.
minaymoryles.
kondlaisah.
anchshizarie.
